### ISSUE TITLE
Example doesn't turn out well

### ISSUE THREAD

**Issue by ChrisRackauckas** [lejon/TSne.jl#20]
The example was probably done on an old version of the code with different hyperparameters. These days... the result using the parameters from the example is really bad.

```julia
using TSne, MNIST

rescale(A, dim::Integer=1) = (A .- mean(A, dim)) ./ max.(std(A, dim), eps())

data, labels = traindata()
data = convert(Matrix{Float64}, data[:, 1:2500])'
# Normalize the data, this should be done if there are large scale differences in the dataset
X = rescale(data, 1)

Y = tsne(X, 2, 50, 1000, 20.0)

using Plots
pyplot()
scatter(Y[:,1], Y[:,2], groups=string.(labels[1:size(Y,1)]))
savefig("tsne.png")
```

![tsne](https://user-images.githubusercontent.com/1814174/38453122-54fb046e-3a05-11e8-812c-00ef4ccb31a2.png)

**Comment by ChrisRackauckas** [comment]
Maybe this could have happened after @alyst 's distance change? I remember the package working months back.

**Comment by alyst** [comment]
@ChrisRackauckas Thanks for the report! Indeed it's because of the #18 changes to `pca()`: I didn't realize that `eigfact()` sorts eigvalues in ascending order. Should be fixed now.

**Comment by lejon** [comment]
Many thanks for the fix @alyst!

**Comment by ChrisRackauckas** [comment]
Could this get a patch release?

**Comment by ChrisRackauckas** [comment]
Yup it did, thanks!

**Comment by alyst** [comment]
JuliaLang/METADATA.jl#14214

**Comment by ChrisRackauckas** [comment]
I am still getting something that doesn't look so good:

```julia
using TSne, MNIST

rescale(A, dim::Integer=1) = (A .- mean(A, dim)) ./ max.(std(A, dim), eps())

data, labels = traindata()
data = convert(Matrix{Float64}, data[:, 1:2500])'
# Normalize the data, this should be done if there are large scale differences in the dataset
X = rescale(data, 1)

Y = tsne(X, 2, 50, 1000, 20.0)

using Plots; plotly()
scatter(Y[:,1],Y[:,2],color=Int.(labels[1:size(Y,1)]))
```

![newplot](https://user-images.githubusercontent.com/1814174/43133420-86604698-8ef3-11e8-9da0-eba72f012231.png)

**Comment by alyst** [comment]
@ChrisRackauckas Is it something new or #21 didn't fix it for you?

**Comment by ChrisRackauckas** [comment]
There are still some clear problems with how it is separating. It should be much clearer on MNIST

**Comment by alyst** [comment]
Yes, I agree. I hadn't tried to reproduce it myself yet. I'm just trying to localize the issue a bit and understand whether it was like that for you back in April, or it's a new regression after the bugfix (there were no recent changes to TSNE, but BLAS/Julia version updates theoretically may affect the results).

**Comment by ChrisRackauckas** [comment]
It was like that back in April. I forgot to file that.

**Comment by alyst** [comment]
Ok, thanks! I plan to upgrade it to 0.7 when I have time in a next few weeks and then take a look at the issue. Unless somebody beats me to it.
