### ISSUE TITLE
Register package in METADATA.jl?

### ISSUE THREAD

**Issue by IainNZ** [lejon/TSne.jl#3]
Hi @lejon,

Are you planning on registering this package in METADATA?

(cc: @rened, who I saw using this package in a Julia issue which let me find this!)

**Comment by lejon** [comment]
Hmm, I don't know... :) What is the procedure for / implications of that? :)

**Comment by rened** [comment]
It would be great to have the package listed!
General info about packages: http://docs.julialang.org/en/release-0.3/manual/packages/#packages
Registering a new package: http://docs.julialang.org/en/release-0.3/manual/packages/#package-development
It would allow people to find the package on http://pkg.julialang.org/ and install it with a simple `Pkg.add("TSne")`. You might get feeback / improvements - but people might also pester you with bug reports ;-)

**Comment by IainNZ** [comment]
Key thing would be discovery, and a way for users to install a known stable version

**Comment by lejon** [comment]
Ok, but I'm guessing not just any joker (like me) are allowed to add packages to the official Julia dist? Is there a process or is it just to fork the METADAT.jl and do a pull request, and then there is some review process? Test suite requirements? Versioning guidelines or is it "free for all"? :)

**Comment by rened** [comment]
Yes, it works by submitting PRs against METADATA. Some checks are automated (checking URLs etc), and the person merging will take a look as well. Tests are not required for inclusion to METADATA, but of course encouraged, and test status will be shown on http://pkg.julialang.org/

Versioning can stay very simple, simply tag a 0.0.1 version using `Pkg.tag(packagename)` and you are all set for registering the package. Most steps should be well covered in http://docs.julialang.org/en/release-0.3/manual/packages/#package-development

**Comment by lejon** [comment]
Ok, thanks! I'll have a look at it if I get some time over.

**Comment by alyst** [comment]
It would be really nice to register the package!

**Comment by Tchanders** [comment]
+1 to registering this!

**Comment by juliohm** [comment]
@lejon please consider registering the package. This is the only way other package writers can rely on your work (i.e. list your package in a  REQUIRE file).

I have explained to you the process in #13, it shouldn't take more than 10min the first time you do it and after you get used to the workflow, it should literally take a mouse click to release a new version.

**Comment by lejon** [comment]
Ok, finally got around to this. 
Added the attobot package to the TSne repo. Let's see how it goes. 
I completely ignored the naming problem by simply using the current one since I seen no convincing argument for anything better (the full name TDistributed...Stoch...Nei...... in my opinion is not better).

**Comment by juliohm** [comment]
I don't think it is a good idea to ignore standards established in METADATA, Julians agreed upon these standards for a reason. Acronyms are just hard to remember, today TSNE is a popular one, in the future perhaps you won't get very useful results by typing it on Google.

CRAN is the biggest example of bad naming: https://cran.r-project.org/web/packages/available_packages_by_date.html

**Comment by alyst** [comment]
For reference, the PR to register the package is JuliaLang/METADATA.jl#10744
I'm not sure it would be merged in the current form, though. One issue is that no packages are allowed to have v1.x.y version before Julia v1.0 is released.

**Comment by juliohm** [comment]
Yes, please follow the standards.

If this is your first release why not call it v0.0.1? That is how most other packages are tagged. I suggest to ask people in METADATA to close the PR, rename the package to something more memorable and then tag v0.0.1.
