### ISSUE TITLE
TSne or Tsne or tsne or ...?

### ISSUE THREAD

**Issue by alyst** [lejon/TSne.jl#8]
Before the package is registered (#3), maybe it's worth to revisit the package name.
The official name of the method is ["t-distributed stochastic neighbor embedding", or t-SNE](https://en.wikipedia.org/wiki/T-distributed_stochastic_neighbor_embedding).
The "t" is small, because it comes from "Student t-distribution".

The alternative names:
- `TSne` (the current one): actually, I often find myself correcting "Tsne" into "TSne" in the scripts. The problem is that for me there is no intuitive explanation why "S" is capital.
-  `Tsne`: is ok, since it follows the "first letter is capital" convention.
- `tSNE`: Matches the official name, but too many capital letters and starts with a small one. Yet julia packages repository contains e.g. `kNN`, so the name is not impossible.
- `TSNE`: Too many capital letters.
- `tsne`: I think it doesn't fit the recommended package name pattern.

**Comment by lejon** [comment]
Yes, tsne would probably be the best I guess. I'm not entirely clear on all the details in getting it registered. Would the GitHub repo name need to be changed? Other than that I guess it is the module name? Is that all?

**Comment by lejon** [comment]
From a quick read I guess the correct thing would be to rename the GitHub repo to "tsne" as well. From what I understand this should not cause too much problems for people that have forked the repo and all followers etc seems to be redirected.

**Comment by alyst** [comment]
Yes, the name of the repo should match. Maybe you can ask @tkelman whether "tsne" is a feasible name for a package.

**Comment by tkelman** [comment]
A lowercase first letter would be discouraged by the module naming conventions. kNN is a very old and deprecated package, and the only exception.

Acronyms are also discouraged.

**Comment by alyst** [comment]
@tkelman so the only valid option is "Tsne" or even "TStochasticNeighborEmbedding"?

**Comment by tkelman** [comment]
I'd personally prefer something like the latter, more explicit and discoverable that way. Tab completion makes long names not such a big deal. Could shorten Stochastic to Stoch or similar maybe.

**Comment by alyst** [comment]
@lejon I think your package deserves better visibility and is quite stable to be registered in the package repository in its current state. I can help you with registering in `METADATA.jl`. The only change that only you, as the owner of the repository, can do is to rename it according to Julia conventions. IIUC, `TStochasticNeighborEmbedding.jl` is the variant that most of the people had agreed with (anticipating potential extensions by another distance metrics it could also be called just `NeighbourEmbedding.jl` or `StochasticNeighbourEmbedding.jl`).

**Comment by tkelman** [comment]
May also want to consider whether you still need to support Julia 0.4, given 0.6 is around the corner - might be worth setting the minimum in REQUIRE to 0.5 before registering, if you don't really need 0.4 support any more

**Comment by alyst** [comment]
I can make a PR upgrading it to Julia 0.5+ prior to registering.

**Comment by juliohm** [comment]
Please register this awesome package as `TStochNeighborEmbedding.jl` :+1: 

Also, please remove the dependencies on RDatasets and MNIST. Is anyone working on this? I can submit a PR today if you want.

**Comment by lejon** [comment]
Done.
